apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-httpd
  labels:
    app: apache-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
